# Generated by Django 5.1.4 on 2024-12-22 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="createdAt",
            new_name="created_at",
        ),
    ]
